// src/lib/showcase/sessions/vo01/examples/todo/Todo.jsx
import React, { useState } from "react";

function TodoApp() {
    const [todo, setTodo] = useState("");
    const [todos, setTodos] = useState([]);

    function handleAddTodo() {
        setTodos([...todos, todo]);
        setTodo("");
    }

    return (
        <div>
            <input value={todo} onChange={(e) => setTodo(e.target.value)} />
            <button onClick={handleAddTodo}>Add</button>
            <ul>
                {todos.map((t) => (
                    <li key={t}>{t}</li>
                ))}
            </ul>
        </div>
    );
}

export default TodoApp;

// src/lib/showcase/sessions/vo01/examples/todo/Todo.svelte
<script lang="ts">
    let todos: string[] = [], newTodo: string = '';
    function addTodo(){
        todos.push(newTodo);
        todos = todos;
        newTodo = '';
    }
</script>

<ul>
    {#each todos as todo}
        <li>{todo}</li>
    {/each}
</ul>
<input type="text" bind:value={newTodo} />
<button on:click={addTodo}>Add</button>
